ignore:
    - "DADependencyInjection/AppDelegate.swift"
    - "DADependencyInjection/ViewController.swift"
    - "DADependencyInjection/Libraries/.*"
    - "DADependencyInjectionTests/.*"
    - "**/*ViewController.swift"
